SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[processed_sessions](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[session_id] [varchar](80) NOT NULL,
	[processed_at] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[processed_sessions] ADD PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[processed_sessions] ADD UNIQUE NONCLUSTERED 
(
	[session_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[processed_sessions] ADD  DEFAULT (getdate()) FOR [processed_at]
GO
